# Generated by Django 3.2.15 on 2023-03-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230312_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='counts',
            new_name='count',
        ),
    ]
