# Generated by Django 3.2.15 on 2023-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_remove_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.CreateModel(
            name='OrderElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('products', models.ManyToManyField(related_name='order_elements', to='foodcartapp.Product', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_elements',
            field=models.ManyToManyField(related_name='order', to='foodcartapp.OrderElements', verbose_name='Элементы заказа'),
        ),
    ]
