# Generated by Django 3.2.15 on 2023-03-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230312_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_surname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_elements',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='orderelements',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_elements', to='foodcartapp.product', verbose_name='Продукт'),
        ),
    ]
