# Generated by Django 3.2.15 on 2023-03-25 09:24
from django.core.validators import MinValueValidator
from django.db import migrations, models
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_order_coast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_coast',
        ),
        migrations.AddField(
            model_name='orderelements',
            name='order_coast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[MinValueValidator(limit_value=0)], verbose_name='Стоимость заказа'),
        ),
    ]
