# Generated by Django 3.2.15 on 2023-03-25 09:40

from django.db import migrations


def fill_old_order_cost(apps, schema_editor):
    OrderElements = apps.get_model('foodcartapp', 'OrderElements')
    for elements in OrderElements.objects.all():
        price = elements.product.price
        coast = price * elements.quantity
        elements.cost = coast
        print('elements =', elements, coast)
        elements.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0049_auto_20230325_0932'),
    ]

    operations = [
        migrations.RunPython(fill_old_order_cost)
    ]
