# Generated by Django 3.2.15 on 2023-03-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(default=1, max_length=300, verbose_name='Комментарий к заказу'),
            preserve_default=False,
        ),
    ]
