# Generated by Django 3.2.15 on 2023-03-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_order_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
