# Generated by Django 3.2.15 on 2023-04-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_order_restaurant_to_cooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, default=111, max_length=300, verbose_name='Комментарий к заказу'),
            preserve_default=False,
        ),
    ]
