# Generated by Django 3.2.15 on 2023-04-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=300, verbose_name='Комментарий к заказу'),
        ),
    ]
