# Generated by Django 3.2.15 on 2023-04-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_alter_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='register_at',
            new_name='order_register_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='restaurant_to_cooking',
            new_name='restaurant_that_cooks',
        ),
        migrations.RenameField(
            model_name='orderelements',
            old_name='coast',
            new_name='order_coast',
        ),
        migrations.AlterField(
            model_name='orderelements',
            name='quantity',
            field=models.IntegerField(max_length=1, verbose_name='Количество'),
        ),
    ]
