# Generated by Django 3.2.15 on 2023-04-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_auto_20230411_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderelements',
            old_name='order_coast',
            new_name='cost',
        ),
    ]
